# Generated by Django 6.0.7 on 2026-07-16 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Collection Name')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dressed in Silence.', max_length=200)),
                ('subtitle', models.CharField(default='SUMMER - AUTUMN 2025', max_length=200)),
                ('product_details', models.CharField(default='Draped Jersey Set - € 420', max_length=200)),
                ('image', models.ImageField(upload_to='editorial_banners/')),
                ('button_link', models.CharField(default='#', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lookbook', 'LOOKBOOK'), ('essay', 'ESSAY'), ('process', 'PROCESS'), ('archive', 'ARCHIVE')], default='lookbook', max_length=50)),
                ('title', models.CharField(default='In Full Bloom', max_length=200)),
                ('tagline', models.CharField(default='A study of softness in the age of noise.', max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='editorial_stories/')),
                ('issue_number', models.CharField(default='ISSUE 07 — 03 2026', max_length=100)),
                ('date_published', models.CharField(default='June 2026', max_length=100)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editorial_quote', models.CharField(default='The quietest clothes are often the loudest statements.', max_length=500)),
                ('shop_look_link', models.CharField(default='/collection-all/', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, help_text='जैसे: SIGNATURE', max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category')),
            ],
        ),
    ]
