# Generated by Django 6.0.7 on 2026-07-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_editorialstory_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default='Ivory / Blush', help_text='जैसे: Black / White', max_length=100),
        ),
    ]
